stages:
  - build

dev_job:
  stage: build
  image: docker:18.06.0-ce-rc1
  only:
    - dev
  tags:
    - docker
  script:
    - docker build -t reg.paradise-soft.com.tw:5000/fileserver-api:latest .
    - docker push reg.paradise-soft.com.tw:5000/fileserver-api:latest


uat_job:
  stage: build
  image: docker:18.06.0-ce-rc1
  only:
    - uat
  tags:
    - docker
  script:
    - docker build -t reg.paradise-soft.com.tw:5000/fileserver-api:uat .
    - docker push reg.paradise-soft.com.tw:5000/fileserver-api:uat

tags_job:
  stage: build
  image: docker:18.06.0-ce-rc1
  only:
    - tags
  tags:
    - docker
  script:
    - docker build --build-arg VERSION=$CI_COMMIT_TAG --build-arg COMMITSHA=$CI_COMMIT_SHA -t reg.paradise-soft.com.tw:5000/fileserver-api:$CI_COMMIT_TAG .
    - docker push reg.paradise-soft.com.tw:5000/fileserver-api:$CI_COMMIT_TAG
